export { default as Dashboard} from './dashboard/Dashboard';
export { default as ForgotPasswordSL } from './forgotPassword/ForgotPasswordSL';
export { default as ForgotPasswordCM } from './forgotPassword/ForgotPasswordCM';
export { default as ForgotPasswordUP } from './forgotPassword/ForgotPasswordUP';
export { default as Login } from './login/Login';
export { default as NotFound } from './notFound/NotFound';
export { default as SignUp } from './signUp/SignUp';
export { default as Userprofile } from './userprofile/Userprofile';
export { default as VerifyNotice } from './verifyNotice/VerifyNotice';
export { default as Landing } from './landing/Landing';
export { default as AdminDashboard } from './adminDashboard/AdminDashboard';
